---
- name: OpenSSH | Make sure we have OpenSSH-server installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["openssh-server"]

- name: OpenSSH | Create default key directory
  file:
    dest: /etc/ssh/authorized_keys
    owner: root
    group: root
    mode: 0644
    state: directory

- name: OpenSSH | Put configuration file in place, validate, restart ssh
  template:
    src: etc_ssh_sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - OpenSSH | reload ssh
    - OpenSSH | restart ssh
